export const BASE_URL = process.env.NEXT_PUBLIC_API_BASEURL
export const UPLOAD_PRESET = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;
export const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
export const API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
export const API_SECRET = process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET